### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by matthewtquinn1** [TrilonIO/angular-application-insights#112]
Hi, me again! 

Are you planning on updating this repository to support Angular 13? :) 

Thank you.

**Comment by brylkovskyi** [comment]
At least would be great if router peer dependency bumped to ^13, otherwise need to `npm install --legacy-peer-deps` to resolve dependency tree

**Comment by MarkPieszak** [comment]
Fixing right now! Apologies I completely missed this one!! 
@matthewtquinn1 @brylkovskyi 

Publishing any minute now as `v9.0.2` 🚢
