### ISSUE TITLE
Add properties and measurements arguments to trackDependency

### ISSUE THREAD

**Issue by jacobslusser** [TrilonIO/angular-application-insights#67]
See:
[https://github.com/Microsoft/ApplicationInsights-JS/issues/725](https://github.com/Microsoft/ApplicationInsights-JS/issues/725)
[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30932](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30932)

Properties and measurements arguments have been added to the `trackDependency` function. Could we get the same?

Thanks.

**Comment by MarkPieszak** [comment]
Yes definitely! Let me get those in tomorrow - apologies on the delay

**Comment by MarkPieszak** [comment]
Took way too long apologies for that!!

Was super swamped setting up **[Trilon.io](https://trilon.io)**.

We're all set though, I actually updated all the Type defs to give more information for intellisense as well. 

7.0.2 pushed to NPM with these updates :)
