### ISSUE TITLE
 Cannot find module '@angular/core'

### ISSUE THREAD

**Issue by katakam43** [TrilonIO/angular-application-insights#71]
Hello, 

I am getting error as below on ng-serve. 

 ../node_modules/@markpieszak/ng-application-insights/dist/index.d.ts(1,37): error TS2307: Cannot find module '@angular/core'.

../node_modules/@markpieszak/ng-application-insights/dist/src/app-insight.service.d.ts(2,26): error TS2307: Cannot find module '@angular/core'. 

I am using Angular 7.

**Comment by MarkPieszak** [comment]
Can you do a wipe of everything and try reinstalling?
Also just to make sure - you're using the latest version of the Package as well?

(Mac/Linux)
```
rm -rf ./node_modules ./package-lock.json && npm i

// rimraf if you're on windows
```

**Comment by katakam43** [comment]
Its fixed. thanks!.
