### ISSUE TITLE
Angular 8 (ivy) - ERROR in There is no format with import statements

### ISSUE THREAD

**Issue by HappyZimmer** [TrilonIO/angular-application-insights#76]
I Get this Error in an Angular 8 Project
ERROR in There is no format with import statements in 'xxx/node_modules/@markpieszak/ng-application-insights' entry-point.

The usage of the Module is:

ApplicationInsightsModule.forRoot({
      instrumentationKeySetLater: true
    }),

**Comment by MarkPieszak** [comment]
Let me take a look and see what we need to update for Angular 8! Apologies

**Comment by cblaettl** [comment]
I experience the same issue, but only if i enable Ivy in `tsconfig.app.json` like this:
```
"angularCompilerOptions": {
    "enableIvy": true
},
```

**Comment by MarkPieszak** [comment]
This may be related to this issue here:
https://github.com/angular/angular/issues/29564

With a potential fix PR here that hasn't been merged yet:
https://github.com/angular/angular/pull/30591

I'll double check to make sure though 📲

**Comment by MarkPieszak** [comment]
Published `@markpieszak/ng-application-insights@8.0.0`

If we can open a new issue if it's still working - let me know!
