### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by rsuk** [TrilonIO/angular-application-insights#82]
Do you have any plans to support Angular 8? Seems to be working ok, but get peer dependencies warnings so I'm wondering if there is still work to do for full support.

**Comment by AndreyBespamyatnov** [comment]
I can do a PR today, probably

**Comment by AndreyBespamyatnov** [comment]
Created: https://github.com/TrilonIO/angular-application-insights/pull/83

**Comment by MarkPieszak** [comment]
Published `@markpieszak/ng-application-insights@8.0.0`

Thanks @andrelmp 	:+1:

If we can open a new issue if it's still working - let me know!

**Comment by AndreyBespamyatnov** [comment]
@MarkPieszak Hi, could you change my name in your comment https://github.com/TrilonIO/angular-application-insights/issues/82#issuecomment-511767790, it is NOT me)

**Comment by MarkPieszak** [comment]
Fixed! That's strange that it did that 😆 
Sorry about that!
