### ISSUE TITLE
Status Code: 400 100: Field 'ai.operation.name' on type 'ContextTagKeys' is too long. Expected: 1024

### ISSUE THREAD

**Issue by Exlord** [TrilonIO/angular-application-insights#84]
Hi, 
Sometimes I am getting this message in the console :

 `Status Code: 400 100: Field 'ai.operation.name' on type 'ContextTagKeys' is too long. Expected: 1024 characters, Actual: 1157`

**Comment by MarkPieszak** [comment]
It looks like a (still open) bug in the underlying SDK 😢 

https://github.com/microsoft/ApplicationInsights-JS/issues/1107

**Comment by MarkPieszak** [comment]
It looks like the underlying issue was closed, maybe this is fixed now? @Exlord

**Comment by MarkPieszak** [comment]
It looks like the underlying issue was closed and a PR was just made (https://github.com/microsoft/ApplicationInsights-JS/pull/1193).

🎸🐈
