### ISSUE TITLE
Angular 9 support 

### ISSUE THREAD

**Issue by jerone** [TrilonIO/angular-application-insights#87]
I'm making an inventory to see if our project is possible to upgrade to Angular 9.

The [`peerDependencies`](https://github.com/TrilonIO/angular-application-insights/blob/master/package.json#L35) in the `package.json` indicates that Angular 9 is supported, but I can't find any documentation that this is true.

My question, does `@markpieszak/ng-application-insights` work with Angular 9?

**Comment by jerone** [comment]
Ping @MarkPieszak 🏓

**Comment by MarkPieszak** [comment]
It should, let me double check and make sure to upgrade everything for angular 10 but it should work as we’re not using any too ng specific here!

**Comment by MarkPieszak** [comment]
We should be all set for Angular 10 in the latest 8.0.2 version!
Sorry for the delay!

**Comment by MarkPieszak** [comment]
I'll close this out for now, but if you can re-open an issue if there's still something wrong with v10, it was fine with testing - made all the changes last night and published 8.0.2 :)
