### ISSUE TITLE
Add missing property `enableAutoRouteTracking` to configuration

### ISSUE THREAD

**Issue by JonoSchoeman** [TrilonIO/angular-application-insights#92]
There is a missing property `enableAutoRouteTracking` from the [Microsoft's Appinsights Javascript configuration](https://github.com/microsoft/ApplicationInsights-JS#configuration).

Could we please add this as part of the configuration?

**Comment by MarkPieszak** [comment]
Hey sorry for the delay, I added all the other missing options as well! There was about 10-15 of them :)
We should be all set, and they should be available via 8.0.3 now. 🎸🎸
