### ISSUE TITLE
Generic type 'ModuleWithProviders<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by aleksandar-kandzhichki** [TrilonIO/angular-application-insights#94]
Hello, I updated to Angular 10 and now I have an issue with the `forRoot` method:

![image](https://user-images.githubusercontent.com/13217235/91023661-7f193100-e5ff-11ea-9f5f-a993a1e95746.png)

It says that ModuleWithProviders usage without a generic type is deprecated, so can we push a version with atleast <any> so Angular builds :)

**Comment by MarkPieszak** [comment]
This should be fixed in the latest 8.0.2 version, let me know if not!

Fixed via 8521606bdcdeb02712817c7158c2639258eb146d
